name: Remote Dispatch Action Initiator

on:
  repository_dispatch:

jobs:
  new_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Bump upstream version
        run: sed -i "s/        - UPSTREAM_VERSION=.*/        - UPSTREAM_VERSION=${{  github.event.client_payload.tag }}/g" docker-compose.yml

      - name: dappnodesdk publish
        run: npx @dappnode/dappnodesdk publish patch --dappnode_team_preset --timeout 2h
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEVELOPER_ADDRESS: "0xf35960302a07022aba880dffaec2fdd64d5bf1c1"

      - name: Commit changes
        run: |
          git config --global user.email "eduadiez@gmail.com"
          git config --global user.name "Eduardo"
          git commit -am "Bumped upstream version to ${{  github.event.client_payload.tag }} and released"
          git push
